# Generated by Django 3.1.5 on 2021-01-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('item', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('endDate', models.DateField(default=0, verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Name', models.CharField(max_length=60, unique=True)),
                ('pas', models.CharField(max_length=50)),
            ],
        ),
    ]
