# Generated by Django 3.1.5 on 2021-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('item', models.CharField(max_length=75)),
                ('dateEnded', models.DateField()),
            ],
        ),
    ]
